//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db539594002Entities : DbContext
    {
        public db539594002Entities()
            : base("name=db539594002Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<resourceextra> resourceextras { get; set; }
        public virtual DbSet<resource> resources { get; set; }
        public virtual DbSet<resourcetype> resourcetypes { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<moduletag> moduletags { get; set; }
        public virtual DbSet<resourcetag> resourcetags { get; set; }
    }
}
